# SSDP multicast routing for Sonos / DLNA / UPnP
#
# LAN   : br-lan.100  / 192.168.1.0/24
# GUEST : br-lan.200 / 192.168.2.0/24
# IOT   : br-lan.300 / 192.168.3.0/24

phyint br-lan.100 enable
phyint br-lan.200 enable
phyint br-lan.300 enable

# LAN -> IoT
mroute from br-lan.100 group 239.255.255.250 to br-lan.300

# Guest -> IoT
mroute from br-lan.200 group 239.255.255.250 to br-lan.300

# IoT -> LAN and Guest
mroute from br-lan.300 group 239.255.255.250 to br-lan.100 br-lan.200
